Strip whitespace from uptime

diff --git a/clearwater-infrastructure/usr/share/clearwater/bin/check-stability b/clearwater-infrastructure/usr/share/clearwater/bin/check-stability
--- a/clearwater-infrastructure/usr/share/clearwater/bin/check-stability
+++ b/clearwater-infrastructure/usr/share/clearwater/bin/check-stability
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 # @file check-stability
 #
@@ -28,9 +28,14 @@ uptime=$( ps -p $pid -o etimes= 2>/dev/null) || { echo -n "No process matching v
 # longer than $aborting_flag_timeout
 /usr/share/clearwater/bin/cw-flag timeout $aborting_flag $aborting_flag_timeout
 
-if /usr/share/clearwater/bin/cw-flag read $aborting_flag\
-   && [ "$uptime" -ge "$required_uptime" ]; then
-  exit 0
-else
+if ! /usr/share/clearwater/bin/cw-flag read $aborting_flag; then
+  echo -n "process is unstable as it is currently aborting" >&2
   exit 1
+elif [ "$uptime" -lt "$required_uptime" ]; then
+  uptime_no_whitespace=$( echo -e $uptime | tr -d '[:space:]')
+  echo -n "process is unstable as it has not been up for long enough
+  ($uptime_no_whitespace s < $required_uptime s)" >&2
+  exit 1
+else
+  exit 0
 fi
