Tidy script up significantly

diff --git a/clearwater-infrastructure/usr/share/clearwater/bin/clearwater-check-config b/clearwater-infrastructure/usr/share/clearwater/bin/clearwater-check-config
--- a/clearwater-infrastructure/usr/share/clearwater/bin/clearwater-check-config
+++ b/clearwater-infrastructure/usr/share/clearwater/bin/clearwater-check-config
@@ -41,6 +41,57 @@ SHARED_CONFIG=$CONFIG_DIR/shared_config
 USER_SETTINGS=$CONFIG_DIR/user_settings
 CLEARWATER_CONFIG=$CONFIG_DIR/config
 
+# Utility function for writing messages to stderr.
+error()
+{
+  echo "ERROR: $@" >&2
+}
+
+# Utility function to get an option from a specific config file.
+# Params:
+#   1 - The option to retrieve
+#   2 - The file to search
+get_option_from_file()
+{
+  opt_name=$1
+  filename=$2
+
+  # We're about to source in a config file so start a new shell to avoid
+  # polluting our environment.  The `${!opt}` is bash indirection - it retrieves
+  # the value of the parameter whose name is the value of `opt`
+  ( source $filename; echo ${!opt_name} )
+}
+
+# Check whether an option is present in a specific config file.
+# Params:
+#   1 - The option to check
+#   2 - The file to search
+is_option_in_file()
+{
+  opt_name=$1
+  filename=$2
+
+  [ -n "$( get_option_from_file $opt_name $filename )" ]
+}
+
+# Check that an option is not in a specific file. If it is, print an error to
+# stderr and return a false return code.
+# Params:
+#   1 - The option to check
+#   2 - The file to search
+check_option_not_in_file()
+{
+  opt_name=$1
+  filename=$2
+
+  if is_option_in_file $opt_name $filename; then
+    error "$opt_name should not be placed in $filename"
+    return 1
+  else
+    return 0
+  fi
+}
+
 # Check that a config file exists and is syntactically and semantically valid.
 # Params:
 #   1 - Either "mandatory" (if the file is required) or "optional" (otherwise).
@@ -53,7 +104,7 @@ check_file()
   # Check that the file exists.
   if [[ ! -e "$filename" ]]; then
     if [[ "$required" = mandatory ]]; then
-      echo "ERROR: $filename does not exist" >&2
+      error "$filename does not exist"
       return 1
     fi
     return 0
@@ -64,59 +115,36 @@ check_file()
 
   # Check that the file is syntactically valid.
   if ! bash -n $filename; then
-    echo "ERROR: $filename is not syntactically valid (see previous errors for details)" >&2
+    error "$filename is not syntactically valid (see previous errors for details)"
     return 1
   fi
 
   return 0
 }
 
-
-# Check that there are no options in shared config that it would be bad to
-# share (e.g. `local_ip`).
-#
-# This function is "unsafe" in the sense that it pollutes the environment, so
-# must be called from within a subshell (which `check_option_locations` does).
-check_option_locations_unsafe()
-{
-  #
-  # ATTENTION
-  #
-  # All variables in this script are in uppercase to avoid clashes with real
-  # options in the config files.
-#
-  # List all the options that definitely shouldn't be shared between nodes.
-  NON_SHARED_OPTIONS="local_ip public_ip public_hostname node_idx etcd_cluster etcd_cluster_key"
-
-  # Load the shared config
-  SHARED_CONFIG_FILE=/etc/clearwater/shared_config
-  source $SHARED_CONFIG_FILE
-
-  # Check each non-shared option in turn, and check its not present in our
-  # environment.
-  RC=0
-  for OPT in $NON_SHARED_OPTIONS; do
-    # The `${!OPT}` use bash indirection - it checks the variable who name is
-    # stored as the value of `OPT`
-    if [[ -n ${!OPT} ]]; then
-      echo "ERROR: $OPT is present in $SHARED_CONFIG_FILE"
-      RC=1
-    fi
-  done
-
-  exit $RC
-}
-
-
+# Check that certain important config options are not put in the wrong place.
 check_option_locations()
 {
-  # Call the function that actually does the checking. We need to call it from
-  # a subshell so export the function first.
-  export -f check_option_locations_unsafe
-  ( check_option_locations_unsafe )
+  local local_rc=0
+
+  # First, check that there are no options in shared config that really
+  # shouldn't be shared.
+  check_option_not_in_file "local_ip"         $SHARED_CONFIG || local_rc=1
+  check_option_not_in_file "public_ip"        $SHARED_CONFIG || local_rc=1
+  check_option_not_in_file "public_hostname"  $SHARED_CONFIG || local_rc=1
+  check_option_not_in_file "node_idx"         $SHARED_CONFIG || local_rc=1
+  check_option_not_in_file "etcd_cluster"     $SHARED_CONFIG || local_rc=1
+  check_option_not_in_file "etcd_cluster_key" $SHARED_CONFIG || local_rc=1
+
+  # Now check that log_level is not set in any file other than user_settings.
+  # If it is it won't work.
+  check_option_not_in_file "log_level" $LOCAL_CONFIG  || local_rc=1
+  check_option_not_in_file "log_level" $SHARED_CONFIG || local_rc=1
+
+  return $local_rc
 }
 
-
+# Check that the config options are valid.
 check_config_values()
 {
   # Run a python script to check the contents of the config file. We need to
