Add is-stable script for grace period checking

diff --git a/clearwater-infrastructure/usr/share/clearwater/bin/is-stable b/clearwater-infrastructure/usr/share/clearwater/bin/is-stable
--- a/clearwater-infrastructure/usr/share/clearwater/bin/is-stable
+++ b/clearwater-infrastructure/usr/share/clearwater/bin/is-stable
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# @file check-uptime
+# @file is-stable
 #
 # Copyright (C) Metaswitch Networks 2017
 # If license terms are provided to you in a COPYING file in the root directory
@@ -11,21 +11,16 @@
 
 # Checks that a process has been running for at least REQUIRED_UPTIME
 # seconds. Returns 0 if it has. Returns a non-zero value if it has not.
-REQUIRED_UPTIME=30
 
-# Bail out and return non-zero if anything goes wrong.
-set -e
-
-# The first command-line argument is the pidfile for the process.
-# The second and third arguments are passed through to the script issue_alarm,
-# for it to use to clear the process-not-ready alarm.
-[ $# = 3 ] || { echo "Usage: check-uptime <pidfile> <issuer> <alarm>" >&2 ; exit 2 ; }
+[ $# = 2 ] || { echo "Usage: check-uptime-no-alarm <pidfile> <required uptime(s)>" >&2 ; exit 2; }
 pidfile=$1
-issuer=$2
-alarm=$3
+required_uptime=$2
 
-if /usr/share/clearwater/bin/is-stable $pidfile $REQUIRED_UPTIME; then
-  /usr/share/clearwater/bin/issue-alarm "$issuer" "$alarm"
+# It's expected that there might not be a pidfile
+pid=$( cat $pidfile 2>/dev/null)
+
+uptime=$( ps -p $pid -o etimes= 2>/dev/null) || { echo -n "No process matching value from pidfile: $pid " >&2 ; exit 1 ; }
+if [ "$uptime" -ge "$required_uptime" ]; then
   exit 0
 else
   exit 1
