Revert changes to poll-http

diff --git a/clearwater-infrastructure/usr/share/clearwater/bin/poll-http b/clearwater-infrastructure/usr/share/clearwater/bin/poll-http
--- a/clearwater-infrastructure/usr/share/clearwater/bin/poll-http
+++ b/clearwater-infrastructure/usr/share/clearwater/bin/poll-http
@@ -23,14 +23,11 @@ http_url=http://$address/ping
 $namespace_prefix curl -f -g -m 2 -s $http_url --write-out %{http_code} 2> /tmp/poll-http.sh.stderr.$$ | tee /tmp/poll-http.sh.stdout.$$ | head -1 | egrep -q "(^OK200$|^503$)"
 rc=$?
 
-# Check the return code and log if appropriate. Due to a bug in Monit, output
-# must consist of one line only.
+# Check the return code and log if appropriate.
 if [ $rc != 0 ] ; then
-  echo -n "HTTP failed to $http_url "   >&2
+  echo HTTP failed to $http_url   >&2
   cat /tmp/poll-http.sh.stderr.$$ >&2
-  echo -n " " >&2
   cat /tmp/poll-http.sh.stdout.$$ >&2
-  echo -n " " >&2
 fi
 rm -f /tmp/poll-http.sh.stderr.$$ /tmp/poll-http.sh.stdout.$$
 
