Add a function to check and wait on CPU idle

diff --git a/clearwater-diags-monitor/usr/share/clearwater/bin/gather_diags_utils b/clearwater-diags-monitor/usr/share/clearwater/bin/gather_diags_utils
--- a/clearwater-diags-monitor/usr/share/clearwater/bin/gather_diags_utils
+++ b/clearwater-diags-monitor/usr/share/clearwater/bin/gather_diags_utils
@@ -57,10 +57,33 @@ get_idle_cpu ()
   sed -e 's/\..*//g'
 }
 
+# Asks a user to either wait for idle CPU, or re-run with --force
+check_and_wait_cpu_idle ()
+{
+  echo "This system is currently running at a higher CPU usage than the configured threshold"
+  echo "The process will wait until we have enough idle CPU, or it can be re-run with the --force flag to skip CPU usage checks"
+  echo "Enter 'y' to continue, and wait for idle CPU, or any other input to exit"
+  read user_input
+  if [ "$user_input" != "y" ]
+  then
+    echo "Aborting command on user input"
+    exit 1
+  else
+    echo "Waiting for enough idle CPU to proceed..."
+  fi
+
+  while [ $(get_idle_cpu) -lt $MIN_IDLE_CPU_FOR_GATHER ]
+  do
+    echo -n "."
+    sleep 2
+  done
+  echo "Wait for idle CPU complete"
+}
+
 # Require confirmation from users to ensure that they wish to run this action
 confirm_user_action ()
 {
-  echo "Gathering diagnostics is a CPU intensive operation, and can lead to disruption of service"
+  echo "Gathering diagnostics can be a CPU intensive operation, and might lead to disruption of service on a system under heavy load"
   echo "To confirm, please enter 'drop calls'"
   read user_input
   if [ "$user_input" != "drop calls" ]
