Add RPM package support

diff --git a/clearwater-diags-monitor/usr/share/clearwater/infrastructure/install/clearwater-diags-monitor.prerm b/clearwater-diags-monitor/usr/share/clearwater/infrastructure/install/clearwater-diags-monitor.prerm
--- a/clearwater-diags-monitor/usr/share/clearwater/infrastructure/install/clearwater-diags-monitor.prerm
+++ b/clearwater-diags-monitor/usr/share/clearwater/infrastructure/install/clearwater-diags-monitor.prerm
@@ -1,9 +1,9 @@
 #!/bin/sh
 
-# @file clearwater-radius-auth.prerm
+# @file clearwater-diags-monitor.prerm
 #
 # Project Clearwater - IMS in the Cloud
-# Copyright (C) 2015  Metaswitch Networks Ltd
+# Copyright (C) 2013  Metaswitch Networks Ltd
 #
 # This program is free software: you can redistribute it and/or modify it
 # under the terms of the GNU General Public License as published by the
@@ -34,39 +34,24 @@
 # under which the OpenSSL Project distributes the OpenSSL toolkit software,
 # as those licenses appear in the file LICENSE-OPENSSL.
 
-#
-# see: dh_installdeb(1)
+. /usr/share/clearwater/infrastructure/install/clearwater-diags-monitor.postinst
 
-set -e
+# Reinstate the original core file pattern.
+[ ! -f /etc/clearwater/diags-monitor/core_pattern.old ] || cat /etc/clearwater/diags-monitor/core_pattern.old > /proc/sys/kernel/core_pattern
+rm -f /etc/clearwater/diags-monitor/core_pattern.old
 
-# summary of how this script can be called:
-#        * <prerm> `remove'
-#        * <old-prerm> `upgrade' <new-version>
-#        * <new-prerm> `failed-upgrade' <old-version>
-#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
-#        * <deconfigured's-prerm> `deconfigure' `in-favour'
-#          <package-being-installed> <version> `removing'
-#          <conflicting-package> <version>
-# for details, see http://www.debian.org/doc/debian-policy/ or
-# the debian-policy package
+# Reinstate original systat config.
+[ ! -f /etc/clearwater/diags-monitor/sysstat.old ] || cp -p /etc/clearwater/diags-monitor/sysstat.old /etc/default/sysstat
+rm -f /etc/clearwater/diags-monitor/sysstat.old
 
-case "$1" in
-    remove|upgrade|deconfigure)
-        /usr/share/clearwater/infrastructure/install/clearwater-radius-auth.postinst
-    ;;
+if [ $1 != "upgrade" ]; then
+  # Remove the temporary diagnostics directory.  Do not remove the dumps
+  # directory, we don't want to delete diags.
+  rm -rf /var/clearwater-diags-monitor/tmp
+fi
 
-    failed-upgrade)
-    ;;
-
-    *)
-        echo "prerm called with unknown argument \`$1'" >&2
-        exit 1
-    ;;
-esac
-
-# dh_installdeb will replace this with shell code automatically
-# generated by other debhelper scripts.
-
-#DEBHELPER#
-
-exit 0
+# Stop clearwater-diags-monitor by deleting it from monit and then stopping it.
+# Use || true to ignore a failure, because set -e is in effect.
+rm -f /etc/monit/conf.d/clearwater-diags-monitor.monit
+reload clearwater-monit &> /dev/null || true
+service clearwater-diags-monitor stop || true
diff --git a/clearwater-snmpd/usr/share/clearwater/infrastructure/install/clearwater-snmpd.prerm b/clearwater-snmpd/usr/share/clearwater/infrastructure/install/clearwater-snmpd.prerm
--- a/clearwater-snmpd/usr/share/clearwater/infrastructure/install/clearwater-snmpd.prerm
+++ b/clearwater-snmpd/usr/share/clearwater/infrastructure/install/clearwater-snmpd.prerm
@@ -1,9 +1,9 @@
 #!/bin/sh
 
-# @file clearwater-radius-auth.prerm
+# @file clearwater-snmpd.prerm
 #
 # Project Clearwater - IMS in the Cloud
-# Copyright (C) 2015  Metaswitch Networks Ltd
+# Copyright (C) 2013  Metaswitch Networks Ltd
 #
 # This program is free software: you can redistribute it and/or modify it
 # under the terms of the GNU General Public License as published by the
@@ -34,39 +34,15 @@
 # under which the OpenSSL Project distributes the OpenSSL toolkit software,
 # as those licenses appear in the file LICENSE-OPENSSL.
 
-#
-# see: dh_installdeb(1)
+. /usr/share/clearwater/infrastructure/install/common
 
-set -e
+# Restore original snmpd.conf 
+[ ! -f /etc/snmp/snmpd.conf.pre-clearwater-snmp ] || mv /etc/snmp/snmpd.conf.pre-clearwater-snmp /etc/snmp/snmpd.conf
 
-# summary of how this script can be called:
-#        * <prerm> `remove'
-#        * <old-prerm> `upgrade' <new-version>
-#        * <new-prerm> `failed-upgrade' <old-version>
-#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
-#        * <deconfigured's-prerm> `deconfigure' `in-favour'
-#          <package-being-installed> <version> `removing'
-#          <conflicting-package> <version>
-# for details, see http://www.debian.org/doc/debian-policy/ or
-# the debian-policy package
+# Clean up Monit configuration for snmpd
+rm -f /etc/monit/conf.d/snmpd.monit
+reload clearwater-monit &> /dev/null || true
 
-case "$1" in
-    remove|upgrade|deconfigure)
-        /usr/share/clearwater/infrastructure/install/clearwater-radius-auth.postinst
-    ;;
-
-    failed-upgrade)
-    ;;
-
-    *)
-        echo "prerm called with unknown argument \`$1'" >&2
-        exit 1
-    ;;
-esac
-
-# dh_installdeb will replace this with shell code automatically
-# generated by other debhelper scripts.
-
-#DEBHELPER#
-
-exit 0
+# Use restart here instead of the normal stop, as we've just taken away
+# monit's control of snmpd
+service snmpd restart || true
